---
- name: Deploy E-Commerce App
  hosts: web
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3


  tasks:

    - name: Update system packages
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add riri to docker group
      user:
        name: riri
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Create app directory
      file:
        path: /app
        state: directory
        owner: riri

    - name: Copy docker-compose file
      copy:
        src: docker-compose.yml
        dest: /app/docker-compose.yml

    - name: Copy nginx config
      copy:
        src: nginx.conf
        dest: /app/nginx.conf

    - name: Run containers
      shell: docker-compose -f /app/docker-compose.yml up -d
      become_user: riri
