name: Full DevOps Pipeline

on:
  push:
    branches: ["main"]

jobs:

  terraform:
    name: Terraform Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    outputs:
      instance_ips: ${{ steps.export.outputs.instance_ips }}

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
      - run: terraform validate
      - run: terraform plan -out=tfplan
      - run: terraform apply -auto-approve tfplan

      - id: export
        run: |
          IPS=$(terraform output -json instance_public_ips | jq -r '.[]' | tr '\n' ',')
          echo "instance_ips=$IPS" >> $GITHUB_OUTPUT

  ansible:
    name: Ansible Deploy
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - uses: actions/checkout@v3

      - run: |
          sudo apt update
          sudo apt install -y ansible jq

      - run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - run: |
          echo "[web]" > inventory.ini
          for ip in $(echo "${{ needs.terraform.outputs.instance_ips }}" | tr ',' ' '); do
            echo "$ip ansible_user=ec2-user ansible_ssh_private_key_file=key.pem" >> inventory.ini
          done

      - run: ansible-playbook -i inventory.ini ansible/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
